import { build } from "esbuild";
import { cp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { resolve, join } from "node:path";
import { execFileSync } from "node:child_process";

const root = resolve(import.meta.dirname, "..");
const out = join(root, "vercel-package");
const marker = join(out, ".beprofit-vercel-package");

try {
  await stat(out);
  if ((await readFile(marker, "utf8")) !== "Generated by scripts/build-vercel.mjs\n") {
    throw new Error(`Refusing to replace unrecognized directory: ${out}`);
  }
  await rm(out, { recursive: true });
} catch (error) {
  if (error.code !== "ENOENT") throw error;
}

await mkdir(out, { recursive: true });
await writeFile(marker, "Generated by scripts/build-vercel.mjs\n");
await cp(join(root, "public"), join(out, "public"), { recursive: true });

await build({
  entryPoints: [join(root, "server.ts")],
  outfile: join(out, "server.cjs"),
  bundle: true,
  platform: "node",
  format: "cjs",
  footer: { js: "module.exports = module.exports.default;" },
  target: "node22",
  packages: "bundle",
  external: ["express"],
  loader: { ".html": "text" },
  logLevel: "warning",
});

await writeFile(join(out, "package.json"), JSON.stringify({
  name: "beprofit-vercel-runtime",
  private: true,
  version: "1.0.0",
  type: "module",
  engines: { node: ">=22" },
  dependencies: { express: "4.21.2" },
}, null, 2) + "\n");

execFileSync("npm", ["install", "--package-lock-only", "--ignore-scripts", "--no-audit", "--no-fund"], {
  cwd: out,
  stdio: "ignore",
});
console.log(`Vercel package ready: ${out}`);
